/* Generated by SharpKit 5 v5.4.4 */

if (typeof(JsTypes) == "undefined")
    var JsTypes = [];
var Shared$ProductModel = {
    fullname: "Shared.ProductModel",
    baseTypeName: "System.Object",
    assemblyName: "Shared",
    Kind: "Class",
    definition: {
        ctor: function (){
            this._Id = 0;
            this._Name = null;
            this._Price = 0;
            System.Object.ctor.call(this);
        },
        Id$$: "System.Int32",
        get_Id: function (){
            return this._Id;
        },
        set_Id: function (value){
            this._Id = value;
        },
        Name$$: "System.String",
        get_Name: function (){
            return this._Name;
        },
        set_Name: function (value){
            this._Name = value;
        },
        Price$$: "System.Decimal",
        get_Price: function (){
            return this._Price;
        },
        set_Price: function (value){
            this._Price = value;
        }
    }
};
JsTypes.push(Shared$ProductModel);

